# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
pt:
  languageCode: pt-br
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  # contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
en:
 languageCode: en-us
 contentDir: content/en
 title: English website title...
 weight: 2
 params:
   description: Site description in English...
 menu:
    main:
      - name: Professional Overview
        url: '#bio'
        weight: 1
      - name: Experience & Education
        url: 'en/experience/'
        weight: 2

